//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace AD.BehaviorTestGenerator.Tests

[<Microsoft.VisualStudio.TestTools.UnitTesting.TestClass>]
type BehaviorTest() =
    let imp = Implementation()
    let behavior = imp |> Behavior
    let check property =
        property >> Async.RunSynchronously |> FsCheck.Check.QuickThrowOnFailure

    [<Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod>]
    member _.``always true`` () = behavior.``always true`` |> check

    [<Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod>]
    member _.``plus is commutative`` () =
        behavior.``plus is commutative`` |> check

    [<Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod>]
    member _.``plus is associative`` () =
        behavior.``plus is associative`` |> check

    interface System.IDisposable with
        member _.Dispose() =
            match imp :> obj with
            | :? System.IDisposable as imp -> imp.Dispose()
            | _ -> ()
