//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace AD.BehaviorTestGenerator.xUnitTests

type BehaviorTest() =
    let check property =
        property >> Async.RunSynchronously |> FsCheck.Check.QuickThrowOnFailure

    member private _.Behavior = Implementation() |> Behavior
    [<Xunit.Fact>]
    member test.``always true`` () = test.Behavior.``always true`` |> check

    [<Xunit.Fact>]
    member test.``plus is commutative`` () =
        test.Behavior.``plus is commutative`` |> check

    [<Xunit.Fact>]
    member test.``plus is associative`` () =
        test.Behavior.``plus is associative`` |> check
