//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace Business.Tests

[<Microsoft.VisualStudio.TestTools.UnitTesting.TestClass>]
type BehaviorTest() =
    let check property =
        property
        >> Async.RunSynchronously
        |> FsCheck.Check.QuickThrowOnFailure

    member private _.Behavior = () |> Implementation |> Behavior

    [<Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod>]
    member test.``create a project``() =
        test.Behavior.``create a project`` |> check

    [<Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod>]
    member test.``getting an unknown project returns None``() =
        test.Behavior.``getting an unknown project returns None``
        |> check
